plugins {
    id 'java'
}

group = 'io.btrace'
version = '0.1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(11)
    }
}

dependencies {
    implementation 'org.slf4j:slf4j-api:2.0.18'
    runtimeOnly 'org.slf4j:slf4j-simple:2.0.18'
    testImplementation platform('org.junit:junit-bom:5.12.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.withType(JavaCompile).configureEach {
    options.release = 11
    options.compilerArgs.addAll(['--add-modules', 'jdk.attach'])
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
    jvmArgs '--add-modules', 'jdk.attach'
}
